# Site settings
title: James Wheaton
description: James Wheaton's Personal Website
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: James Wheaton
user_description: I am a technical writer who is passionate about distilling complex information into an easy-to-read format for users. I enjoy using my technical background and communication expertise to create useful documentation for both end-users and developers. 
user_title: Technical Writer
email: jamesfwheaton@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
github_username: jamesfwheaton
baseurl: ""
url: "https://jamesfwheaton.github.io"
